#!/usr/bin/env bash
#display numbers 1 to 100 fizz buzz

n=1

while [ $n -lt 101 ]
do
	if [ $n=$((n*15)) ]
	then
		echo "FizzBuzz"
		if [ $n=$((n*3)) ]
		then
			echo "Fizz"
		fi
		if [ $n=$((n*5)) ]
		then
			echo "Buzz"
		fi
	else
		echo "$n"
	fi
	((n++))
done
