#!/usr/bin/env bash
#displays Best School 10 times
n=1

while [ $n -lt 11 ]
do
	if [ $n = 4 ]
	then
		echo "bad Luck"

	elif [ $n = 8 ]
	then
		echo "good Luck"
	else
		echo "Best School"
	fi
	(( n++ ))
done
