#!/usr/bin/env bash
#use of if else infor about file

sch="school"
if [ -e "$sch" ]
then
	echo "school file exists"
	if [ !-s "$sch" ]
	then
		echo "school file is empty"
	else
		echo "school files is not empty"
	fi
	if [ -f "$sch" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
		
