#!/usr/bin/env bash
#use of if else infor about file

if [ -e school ]
then
	echo "school file exists"
	if [ -s school ]
	then
		echo "school file is not empty
	else
		echo "school files is empty"
	fi
	if [ -f school]
	then
		echo "school is a regular file"
	fi
else
	school "school file does not exist"
fi
		
