#!/usr/bin/env bash
#rip
echo $$ > /var/run/myscript.pid

trap "echo I hate the kill command; rm -fr /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no Love me?!" SIGINT
trap "rm -fr /var/run/myscript.pid; exit" SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
