#!/usr/bin/env bash
#control the beast

if [ "${1}" == "stop" ]
then
	echo "manage_my_process stopped"
	pkill -f /var/run/my_process.pid
	rm /var/run/my_process.pid

elif [ "${1}" == "start" ]
then
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "${1}" == "reset" ]
then
	pkill -f "/var/run/my_process.pid"
	rm /var/run/my_process.pid
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	Usage: manage_my_process {start|stop|restart}

fi
